language: node_js
node_js:
- "0.10"
- "0.12"
- "4.1"
- "4.2"
- "5.0"
before_install:
- npm install -g codeclimate-test-reporter
after_script:
- npm run coverage
- codeclimate < coverage/lcov.info
env:
- NODE_ENV=test
